### ISSUE TITLE
When the Network Plug is selected, the Settings app just close itself

### ISSUE THREAD

**Issue by Jocadbz** [elementary/switchboard-plug-network#306] opened 2021-08-11 17:18 UTC
When i was trying to configure a network, i opened the settings app, and selected the Network plug. Then, the settings app just closed itself. I tried multiple times and the issue still persist.
**STEPS TO REPRODUCE**
**1.** Open the settings app
**2.** Click on the settings app
**Expected Behaviour** : 
The Network plug should open with no issues

**Comment by danrabbit** [comment] 2021-08-11 17:30
Hey thanks for your issue report. This sounds like it's probably a duplicate of https://github.com/elementary/switchboard-plug-network/issues/294

Closing as duplicate

**Closed by danrabbit** 2021-08-11 17:30 UTC
