### ISSUE TITLE
Wifi not working in setup...

### ISSUE THREAD

**Issue by LinkfandosYT** [elementary/switchboard-plug-network#350] opened 2023-03-16 17:03 UTC
### What Happened?

Ya know, when you install the Operating system for the first time... There is this little windows that shows up to create an user , an password ... But he also ask you to connect to the internet. And, that, is not working during setup.
Also Elementary is super cool thanks guys for the work you have made i am supporting you at 100% <3

### Steps to Reproduce

1-Install the OS,
2-Setup few things,
3-Wifi connection is broken :/

### Expected Behavior

I think i dont have to describe...

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
nothing. I don't have access to debug during setup.
```

### Hardware Info

Yeah, cool office computer, an hp... I3 4 gb of ram... The basics ya know.

**Comment by danirabbit** [comment] 2023-12-04 17:40
This is a duplicate of https://github.com/elementary/greeter/issues/615 :)

**Closed by danirabbit** 2023-12-04 17:40 UTC
