### ISSUE TITLE
Network Manager Wireguard

### ISSUE THREAD

**Issue by BMiZEL** [elementary/switchboard-plug-network#363] opened 2023-10-26 07:04 UTC
### Problem

Followed the Instructions and it did not work in Elementary OS 7.1 - https://github.com/max-moser/network-manager-wireguard/ 

Whilst trying to update to a new Kernel, it refused to update, due to a problem with WG and eventually had to reinstall Elementary to fix the issue.

### Proposal

Would be amazing if this could be natively implemented, like OpenVPN

**Comment by lenemter** [comment] 2023-10-26 07:11
I'll close this as duplicate of https://github.com/elementary/switchboard-plug-network/issues/286. The work to add Wireguard support is almost complete and should be available in OS 7 soon.

**Closed by lenemter** 2023-10-26 07:11 UTC

**Comment by BMiZEL** [comment] 2023-10-26 07:16
Amazing, thanks!
