### ISSUE TITLE
Dark child window with light theme enabled (EOS 6 Beta)

### ISSUE THREAD

**Issue by KarkanAlzwayed** [elementary/switchboard-plug-network#295] opened 2021-05-15 19:24 UTC
## What Happened
When opening settings/network then clicking the "setting" button in front of my connected wifi name, the child "editing [Network name]" that pops up is dark themed even thought the whole system theme is set to "default" which is obviously light. Don't know if this is intentional or a bug. 

## Expected Behavior
All windows should follow the same chosen global theme.

## Steps to Reproduce
Open settings/network then in front of your network name, click the "settings" button to get the child window that is used to edit your network.

## Platform Information
EOS 6 Beta
![Screenshot from 2021-05-15 15-15-00](https://user-images.githubusercontent.com/49320606/118375695-58d26180-b591-11eb-87d8-2a5216ff23b2.png)

**Comment by danrabbit** [comment] 2021-05-18 18:27
Hrm, this dialog comes from network manager, so it shouldn't be dark styled at all. OP have you modified your system in any way other than through System Settings? Such as with a tweaks app?

**Comment by KarkanAlzwayed** [comment] 2021-05-18 18:46
@danrabbit I have tweaks installed but I'm using it for minimize button only in this instance. I do use it sometimes to change the folders to different colors. I'll double check and make sure I am using the default icons and try to recreat it.

**Comment by danrabbit** [comment] 2021-05-18 19:31
@KarkanAlzwayed I have not read the source code, but I believe it does something with trying to force a dark style. I can't reproduce this issue and the only thing I can think that would cause it is some hack like tweaks

Closing as "Incomplete" until it can be reproduced on a system without tweaks

**Closed by danrabbit** 2021-05-18 19:31 UTC

**Comment by KarkanAlzwayed** [comment] 2021-05-18 20:55
@danrabbit would just removing tweaks suffice, or should I reinstall? I don't mind reinstalling at all as I've volunteered to test anyway.

**Comment by danrabbit** [comment] 2021-05-18 20:57
@KarkanAlzwayed I don't know the answer to that since I don't know what tweaks is doing. You should bring it up with the tweaks maintainer

**Comment by KarkanAlzwayed** [comment] 2021-05-18 21:25
@danrabbit no worries. I'll try both and report back. Thank you.

**Comment by KarkanAlzwayed** [comment] 2021-05-18 22:47
@danrabbit you were right, it WAS the tweaks apps. All good now. Sorry for the confusion.

**Comment by KarkanAlzwayed** [comment] 2021-05-20 03:11
@danrabbit ok, so I reinstalled the beta from scratch. No tweaks or any other third part stuff. This is just out of the box. While on default mode (light) the child window is themed correctly, but on dark, it is still light. Not sure if it is supposed to follow the global theme or not. See screenshot
![Screenshot from 2021-05-19 23-07-12@2x](https://user-images.githubusercontent.com/49320606/118913430-75ef9300-b8f7-11eb-8cf5-3a718562b965.png)

**Comment by danrabbit** [comment] 2021-05-20 03:13
@KarkanAlzwayed this dialog comes from GNOME Network Manager, so no it will not follow the dark style.

**Comment by KarkanAlzwayed** [comment] 2021-05-20 03:21
@danrabbit Thank you, sir.
