### ISSUE TITLE
feature request for cisco VPN

### ISSUE THREAD

**Issue by zqmuser** [elementary/switchboard-plug-network#73] opened 2017-10-18 16:07 UTC
I got cisco VPN (vpnc) to work, but I have to use the command line and retype the information every time.

Please include this by default and make it accessible via the networks gui.

**Comment by arshubham** [comment] 2019-10-27 20:18
@zqmuser Please share a sample conf file for the above and instruction how to use it.

**Comment by zqmuser** [comment] 2019-10-29 13:18
There are any number of ways you could make a config file; XML, name:value pairs.  When you enter the same information every time, I like a commented file like this

myorg.webvpn.ip.com   # IPSec gateway
insidefirewall    # IPSec ID
23klafs903284   # IPSec secret
myname@ip.com   # username
jjkweoi  # password

Since you are putting password and secret in a file, you would probably encrypt those and require a password to connect, like this

sudo vpnc -id insidefirewall
Enter password:

Where this last password is your login password on the current system.

Since some of the data in the config file is encrypted, there would be a different command line flag to enter the data, check that the connection works, then create the config file with the encrypted data and permissions so only you can read/write it.  

The config file might be named something like .vpnc.insidefirewall and be located in your home directory.  

There are probably dozens of ways to implement this, and some may be better than the idea I have given here.  I will leave the implementation to the vpnc developers.

The point is that those shared secrets are usually long, complex strings, so it is a pain typing it in every time.  Copying the info from an online password database gets ugly when creating the VPN connection can sever your connection to the online password database.

**Comment by arshubham** [comment] 2019-10-31 05:09
@zqmuser I looked some more into it network manager provides `network-manager-vpnc`  plugin for vpnc protocols `sudo apt install network-manager-vpnc`
![image](https://user-images.githubusercontent.com/14235191/67920462-5afce700-fbca-11e9-99a9-6076b7ca967b.png)

Does it cover your usecase. I believe importing the config file by `Import a Saved VPN Configration Option` will work here.

**Comment by danrabbit** [comment] 2019-11-05 01:02
Closing since OP has not responded. Will reopen if the issue persists :)

**Closed by danrabbit** 2019-11-05 01:02 UTC
Labels: Status: Incomplete

**Comment by janxkoci** [comment] 2020-02-11 13:15
I use `vpnc` exactly this way and I can confirm it works (also importing the config file). You can keep it closed :wink:
