### ISSUE TITLE
No way to edit VPN connections without connecting?

### ISSUE THREAD

**Issue by xfbs** [elementary/switchboard-plug-network#121] opened 2018-04-26 22:32 UTC
If I open the network settings and go to the VPN page, the only way (I can see) to edit a network is by clicking on it, which causes my system to connect on it, and then on the top where it shows the connected network, clicking the settings button. There doesn't seem to be a way to edit a connection without connecting to it first (from what I can tell?)

**Comment by jlnr** [comment] 2018-04-27 11:07
I was also confused by this. As a workaround, you can click "Edit Connections" at the bottom, and then edit the VPN connection from there.

**Comment by peteruithoven** [comment] 2018-10-01 15:34
I think this is a duplicate of: https://github.com/elementary/switchboard-plug-network/issues/7

**Closed** 2019-10-30 16:56 UTC
